In [85]:
import pandas as pd
year_15=pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/894/813759/2015.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260518%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260518T143236Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=660ef0c1d836577a519743ea9569fdfa96708c8350830acac2f6ffed185a941290cae82dfa8d97fda1a590f8b9b8e61fe0e14dbecc253d6e143d9d7e1d9a68e90d918339e49c7a3303a276cdb6205916a752079b7a6b0bc49ff71a992fadc7a80a5ed5b5d0eab5c3e25b5295df6507723fa256435ba33dbc994da35c0373be6f21ce368f2f220ad3c4aef053c6448de1beead8a7c7f9ccffc226de20de8e01f049395002ee46db9323bbf23944ef8ee3a8400f1892469f9727b94ffaefee03cf061b5b0cba595e4f8cb90f7b8a39703c0bf99e1063e8961f24d8c07bf81d0856ab06222460dd1291022685be655f0dae506b1fc0a08fad4c00a675a7fef81896')
year_16=pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/894/813759/2016.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260518%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260518T143807Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=21c4ae0b26da1937076eaee4484c372048360264317dae15250f03f24cd644c729db5e731c286c7fdb86f66de61f09683f11ac0aaf583bc5b2c8bd5facb7bf7a429c079c45cf5101a10b2ad99fc73e82009cedae5f7f3d5a7c71fbe02b18fced45793b6a3806c7d380a648827305a8f9b3d06542cc455ebbeef49d3ec944d7da39609be039a5b750d231e95cafa12b8aa4d1a8f11bba78f05de8899b0c2f255f1deae4f84269f1cd10f1722e88bd3ee9d4735790a7a17dbe07d8348cef0a2b5820434060c7e066999f53aca399871f3e7d194f6ca427484fc960171d1bcb5a0c689f3775aaffd60b8a6bb25c086c7975d389bc4a30977c6d5a8d59b9c8447780')
year_17=pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/894/813759/2017.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260518%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260518T143826Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=4330a1932bfae33dd2ff580be778d88b834a9c7fdf3762c8c626a42989289536cafbe836e12756a6e7a3d1b6c3a6e3fd39c0558e8297665c623e8c7f0fd75ceee03f03451cdfe11b454dc55d8cd7cf2a45acc8d324cc81c1b8be430e23f14354dd37fa27a99f7b934be959ab211508cd5fdd7d492e668f1c5bc1d72a642843ae730757fb9b0e5d1d3c7dd8b7666d2f3aa2f9bdb68abc5d16a98a500b30301f5ec7c911787cf5a04e22bf250c39aa21c4101dad28b546e5e4238f11366ceefae0c6b79f08988b554da0491b4cf5a586809116a4afcb813df2f0b3f83ab43e1c0d7fa47b9f7c7e29645d2beb958139e489393a073d973eae918b2bd591fa89c857')
year_18=pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/894/813759/2018.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260518%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260518T143233Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8db2701f2716d60dc70fdc54468415d363c139470a9319cd91ebaf418bb5d6403d650070443c295bc659d0d19da636d39d6690d1d70cf511933363c92ca723d66e72198178149f1040fa0f2150176a040b068b3a5eb8ce37c539c470908acab6fbbaf38e596174b8b02d6e7ba1b4450586926dcfd997e3813e32e43e1b5d948b0de8721217830d248d5c6aef445d3d7eab2db38d9e8f895ee869f26f1ca215f7fe895f76d1f6b8ebffdb193031a95d3b610128b0e2c1201dc1b4fcc10387f2e04d5b53e5d63e92c267bd133cbb303361ea5ef51cf8527c34b2fc6efebe491fa3b08ae5ba635cff3ebd094bdeec458b9632419f264a7596d1e78c4cb0256735dd')
year_19=pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/894/813759/2019.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260518%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260518T143240Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=5542af04ff2d969ae6cb3a586e641e4b1c287f268d088ce687b81052e38ba31a2135ee1a2b2453aa5b90bb1607c191b0d68ea201ce393d443a7046ea64d1f6c7522c53bd871f1ced2dd34909bafb6c9a189ce07f0d8308098323fcaa517eea1b1b467fadb22054af01cf6fdfc397ad83404cb8fee3ac8b12b7ae749fdc768d793a75dcf50c507b55f616d0b567a26aa15d07c816e871b7342e73f534275619a7aa148a99b7cb2b8aae9d739fa94b1638d63803fdbc9f26567f003486a07d9af8bf74438c46f4a8694f65c18b5fbd7ddea2cfabf40b47ecb80bdbab9ec5b0321da4637f1383eeefdc33d587c998894bc46edf7f31cda16ac1cb2f162c325e6d9c')

In [86]:
display(year_15.head().tail())
display(year_16.head())
display(year_17.head())
display(year_18.head())
display(year_19.head())

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [87]:
def clean_column_names(df):
    df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace(".", "_").str.lower()
    return df

clean_column_names(year_15)
clean_column_names(year_16)
clean_column_names(year_17)
clean_column_names(year_18)
clean_column_names(year_19)

column_mapping = {"gdp": "gdp_percapita","health": "life_expectancy","score": "happiness_score","rank": "happiness_rank","corruption": "government_corruption","country": "country","social": "family","freedom": "freedom"}
def rename_columns(df, mapping):
    new_columns = []
    for col in df.columns:
        new_name = col
        for key, value in mapping.items():
            if key in col:
                new_name = value
                break
        new_columns.append(new_name)
    df.columns = new_columns
    return df

year_15=rename_columns(year_15, column_mapping)
year_16=rename_columns(year_16, column_mapping)
year_17=rename_columns(year_17, column_mapping)
year_18=rename_columns(year_18, column_mapping)
year_19=rename_columns(year_19, column_mapping)

display(year_15.columns)
display(year_16.columns)
display(year_17.columns)
display(year_18.columns)
display(year_19.columns)

Index(['country', 'region', 'happiness_rank', 'happiness_score',
       'standard_error', 'gdp_percapita', 'family', 'life_expectancy',
       'freedom', 'government_corruption', 'generosity', 'dystopia_residual'],
      dtype='str')

Index(['country', 'region', 'happiness_rank', 'happiness_score',
       'lower_confidence_interval', 'upper_confidence_interval',
       'gdp_percapita', 'family', 'life_expectancy', 'freedom',
       'government_corruption', 'generosity', 'dystopia_residual'],
      dtype='str')

Index(['country', 'happiness_rank', 'happiness_score', 'whisker_high',
       'whisker_low', 'gdp_percapita', 'family', 'life_expectancy', 'freedom',
       'generosity', 'government_corruption', 'dystopia_residual'],
      dtype='str')

Index(['happiness_rank', 'country', 'happiness_score', 'gdp_percapita',
       'family', 'life_expectancy', 'freedom', 'generosity',
       'government_corruption'],
      dtype='str')

Index(['happiness_rank', 'country', 'happiness_score', 'gdp_percapita',
       'family', 'life_expectancy', 'freedom', 'generosity',
       'government_corruption'],
      dtype='str')

In [88]:
#Checking for duplicates in all data frames:
display(year_15.duplicated().sum())
display(year_16.duplicated().sum())
display(year_17.duplicated().sum())
display(year_18.duplicated().sum())
display(year_19.duplicated().sum())

np.int64(0)

np.int64(0)

np.int64(0)

np.int64(0)

np.int64(0)

In [89]:
#Checking null values in all data frames:
display(year_15.isna().sum())
display(year_16.isna().sum())
display(year_17.isna().sum())
display(year_18.isna().sum())
display(year_19.isna().sum())

#Result: only 1 null value in the corruption column in year 2018

country                  0
region                   0
happiness_rank           0
happiness_score          0
standard_error           0
gdp_percapita            0
family                   0
life_expectancy          0
freedom                  0
government_corruption    0
generosity               0
dystopia_residual        0
dtype: int64

country                      0
region                       0
happiness_rank               0
happiness_score              0
lower_confidence_interval    0
upper_confidence_interval    0
gdp_percapita                0
family                       0
life_expectancy              0
freedom                      0
government_corruption        0
generosity                   0
dystopia_residual            0
dtype: int64

country                  0
happiness_rank           0
happiness_score          0
whisker_high             0
whisker_low              0
gdp_percapita            0
family                   0
life_expectancy          0
freedom                  0
generosity               0
government_corruption    0
dystopia_residual        0
dtype: int64

happiness_rank           0
country                  0
happiness_score          0
gdp_percapita            0
family                   0
life_expectancy          0
freedom                  0
generosity               0
government_corruption    1
dtype: int64

happiness_rank           0
country                  0
happiness_score          0
gdp_percapita            0
family                   0
life_expectancy          0
freedom                  0
generosity               0
government_corruption    0
dtype: int64

In [90]:
common_columns = set(year_15.columns) & set(year_16.columns) & set(year_17.columns)& set(year_18.columns) & set(year_19.columns)

common_columns

{'country',
 'family',
 'freedom',
 'gdp_percapita',
 'generosity',
 'government_corruption',
 'happiness_rank',
 'happiness_score',
 'life_expectancy'}

In [31]:
import pycountry

In [100]:
#Clean country columns in all data frames using the library 'pycountry':
def clean_country_name(country):
    country = country.strip()
    try:
        return pycountry.countries.lookup(country).name
    except LookupError:
        return country

for df in [year_15, year_16, year_17, year_18, year_19]: df["country_clean"] = df["country"].apply(clean_country_name)

In [101]:
(year_15["country"] != year_15["country_clean"]).sum()

np.int64(11)

In [102]:
display(year_15["country"].nunique())
display(year_15["country_clean"].nunique())

158

158

In [109]:
#Checking which country names were changed in the cleaning:
year_15.loc[year_15["country"] != year_15["country_clean"],["country", "country_clean"]].drop_duplicates()

            country                      country_clean
22        Venezuela  Venezuela, Bolivarian Republic of
30   Czech Republic                            Czechia
37           Taiwan          Taiwan, Province of China
46      South Korea                 Korea, Republic of
50          Bolivia    Bolivia, Plurinational State of
51          Moldova               Moldova, Republic of
74          Vietnam                           Viet Nam
98             Laos   Lao People's Democratic Republic
109            Iran          Iran, Islamic Republic of
145        Tanzania       Tanzania, United Republic of
155           Syria               Syrian Arab Republic

In [114]:
year_16.loc[year_16["country"] != year_16["country_clean"],["country", "country_clean"]].drop_duplicates()

            country                      country_clean
26   Czech Republic                            Czechia
34           Taiwan          Taiwan, Province of China
43        Venezuela  Venezuela, Bolivarian Republic of
54          Moldova               Moldova, Republic of
57      South Korea                 Korea, Republic of
58          Bolivia    Bolivia, Plurinational State of
95          Vietnam                           Viet Nam
101            Laos   Lao People's Democratic Republic
104            Iran          Iran, Islamic Republic of
148        Tanzania       Tanzania, United Republic of
155           Syria               Syrian Arab Republic

In [122]:
year_17.loc[year_17["country"] != year_17["country_clean"],["country", "country_clean"]].drop_duplicates()

            country                      country_clean
22   Czech Republic                            Czechia
54      South Korea                 Korea, Republic of
55          Moldova               Moldova, Republic of
57          Bolivia    Bolivia, Plurinational State of
81        Venezuela  Venezuela, Bolivarian Republic of
93          Vietnam                           Viet Nam
107            Iran          Iran, Islamic Republic of
151           Syria               Syrian Arab Republic
152        Tanzania       Tanzania, United Republic of

In [115]:
year_18.loc[year_18["country"] != year_18["country_clean"],["country", "country_clean"]].drop_duplicates()

            country                      country_clean
20   Czech Republic                            Czechia
25           Taiwan          Taiwan, Province of China
56      South Korea                 Korea, Republic of
61          Bolivia    Bolivia, Plurinational State of
66          Moldova               Moldova, Republic of
94          Vietnam                           Viet Nam
101       Venezuela  Venezuela, Bolivarian Republic of
105            Iran          Iran, Islamic Republic of
109            Laos   Lao People's Democratic Republic
149           Syria               Syrian Arab Republic
152        Tanzania       Tanzania, United Republic of

In [107]:
year_19.loc[year_19["country"] != year_19["country_clean"],["country", "country_clean"]].drop_duplicates()

            country                      country_clean
19   Czech Republic                            Czechia
24           Taiwan          Taiwan, Province of China
53      South Korea                 Korea, Republic of
60          Bolivia    Bolivia, Plurinational State of
70          Moldova               Moldova, Republic of
93          Vietnam                           Viet Nam
104            Laos   Lao People's Democratic Republic
107       Venezuela  Venezuela, Bolivarian Republic of
116            Iran          Iran, Islamic Republic of
148           Syria               Syrian Arab Republic
152        Tanzania       Tanzania, United Republic of

In [145]:
display(year_15.region.isna().sum())
display(year_16.region.isna().sum())

np.int64(0)

np.int64(0)

In [119]:
# Checking if the region column is replicable for the years that don't include it and if there are duplicates or null values:
display(year_15['region'].value_counts())
display(year_16.region.value_counts())
display(len(year_15.country))
display(len(year_16.country))
display(len(year_17.country))
display(len(year_18.country))
display(len(year_19.country))

# Create a dictionary containing all the countries in the df for year 15 and 16 and drop duplicates:
country_region_map = (pd.concat([year_15[["country_clean", "region"]],year_16[["country_clean", "region"]]]).drop_duplicates().dropna())
country_region_map.groupby("country_clean")["region"].nunique().sort_values(ascending=False)
country_region_dict = country_region_map.drop_duplicates("country_clean").set_index("country_clean")["region"]

region
Sub-Saharan Africa                 40
Central and Eastern Europe         29
Latin America and Caribbean        22
Western Europe                     21
Middle East and Northern Africa    20
Southeastern Asia                   9
Southern Asia                       7
Eastern Asia                        6
North America                       2
Australia and New Zealand           2
Name: count, dtype: int64

region
Sub-Saharan Africa                 38
Central and Eastern Europe         29
Latin America and Caribbean        24
Western Europe                     21
Middle East and Northern Africa    19
Southeastern Asia                   9
Southern Asia                       7
Eastern Asia                        6
North America                       2
Australia and New Zealand           2
Name: count, dtype: int64

158

157

155

156

156

In [146]:
# Creating the region column for the dataframes year 2016, 2017, 2018:
year_17["region"] = year_17["country_clean"].map(country_region_dict)
year_18["region"] = year_18["country_clean"].map(country_region_dict)
year_19["region"] = year_19["country_clean"].map(country_region_dict)

In [147]:
#Checking if after the creation there are any null values in the region column:
display(year_17[year_17["region"].isna()]["country_clean"].unique())
display(year_18[year_18["region"].isna()]["country_clean"].unique())
display(year_19[year_19["region"].isna()]["country_clean"].unique())

<StringArray>
['Taiwan Province of China', 'Hong Kong S.A.R., China']
Length: 2, dtype: str

<StringArray>
['Trinidad & Tobago', 'Northern Cyprus']
Length: 2, dtype: str

<StringArray>
['Trinidad & Tobago', 'Northern Cyprus', 'North Macedonia', 'Gambia']
Length: 4, dtype: str

In [155]:
#Fix manually the missing values which appear to be non corrected countries using the library:
country_name_fixes = {"Taiwan Province of China": "Taiwan, Province of China","Hong Kong S.A.R., China": "Hong Kong","Trinidad & Tobago": "Trinidad and Tobago","Northern Cyprus": "Cyprus","North Macedonia": "North Macedonia","Gambia": "Gambia"}
for df in [year_17, year_18, year_19]: df["country_clean"] = df["country_clean"].replace(country_name_fixes)

In [158]:
# Check once the names of countries are corrected if they are still null and if so is a problem with these countries not being in the original dictionary so we will have to add them manually for regions:
display(year_17[year_17["region"].isna()]["country_clean"].unique())
display(year_18[year_18["region"].isna()]["country_clean"].unique())
display(year_19[year_19["region"].isna()]["country_clean"].unique())

manual_region_fixes = {"Taiwan, Province of China": "Eastern Asia","Hong Kong": "Eastern Asia","Trinidad and Tobago": "Latin America and Caribbean","Cyprus": "Middle East and Northern Africa","North Macedonia": "Central and Eastern Europe","Gambia": "Sub-Saharan Africa"}
year_17["region"] = year_17["region"].fillna(year_17["country_clean"].map(manual_region_fixes))
year_18["region"] = year_18["region"].fillna(year_18["country_clean"].map(manual_region_fixes))
year_19["region"] = year_19["region"].fillna(year_19["country_clean"].map(manual_region_fixes))

<StringArray>
['Taiwan, Province of China', 'Hong Kong']
Length: 2, dtype: str

<StringArray>
['Trinidad and Tobago', 'Cyprus']
Length: 2, dtype: str

<StringArray>
['Trinidad and Tobago', 'Cyprus', 'North Macedonia', 'Gambia']
Length: 4, dtype: str

In [159]:
# Checking one final time for nulls:
display(year_17[year_17["region"].isna()]["country_clean"].unique())
display(year_18[year_18["region"].isna()]["country_clean"].unique())
display(year_19[year_19["region"].isna()]["country_clean"].unique())

<StringArray>
[]
Length: 0, dtype: str

<StringArray>
[]
Length: 0, dtype: str

<StringArray>
[]
Length: 0, dtype: str

In [160]:
# Create year column in each data framing before we create the final data frame with all the info:
year_15["year"] = 2015
year_16["year"] = 2016
year_17["year"] = 2017
year_18["year"] = 2018
year_19["year"] = 2019

In [163]:
# Choosing the columns we want in our finally clean dataframe:
columns_to_keep = ["happiness_rank","year","country_clean","region","happiness_score","gdp_percapita","life_expectancy","family","freedom","generosity","government_corruption"]
final_15 = year_15[columns_to_keep]
final_16 = year_16[columns_to_keep]
final_17 = year_17[columns_to_keep]
final_18 = year_18[columns_to_keep]
final_19 = year_19[columns_to_keep]

hapy_country_df = pd.concat([final_15, final_16, final_17, final_18, final_19],ignore_index=True)
hapy_country_df = hapy_country_df.rename(columns={"country_clean": "country"})

In [168]:
# Exploring the final dataframe:
display(hapy_country_df.shape)
display(hapy_country_df.columns)
display(hapy_country_df["year"].value_counts().sort_index())
display(hapy_country_df["region"].value_counts())
display(hapy_country_df["country"].nunique())
display(hapy_country_df[["year", "region"]].value_counts())

(782, 11)

Index(['happiness_rank', 'year', 'country', 'region', 'happiness_score',
       'gdp_percapita', 'life_expectancy', 'family', 'freedom', 'generosity',
       'government_corruption'],
      dtype='str')

year
2015    158
2016    157
2017    155
2018    156
2019    156
Name: count, dtype: int64

region
Sub-Saharan Africa                 196
Central and Eastern Europe         145
Latin America and Caribbean        111
Western Europe                     103
Middle East and Northern Africa     98
Southeastern Asia                   44
Southern Asia                       35
Eastern Asia                        30
North America                       10
Australia and New Zealand           10
Name: count, dtype: int64

166

year  region
2015  Sub-Saharan Africa                 40
2019  Sub-Saharan Africa                 40
2017  Sub-Saharan Africa                 39
2018  Sub-Saharan Africa                 39
2016  Sub-Saharan Africa                 38
2015  Central and Eastern Europe         29
2016  Central and Eastern Europe         29
2017  Central and Eastern Europe         29
2018  Central and Eastern Europe         29
2019  Central and Eastern Europe         29
2016  Latin America and Caribbean        24
2015  Latin America and Caribbean        22
2017  Latin America and Caribbean        22
2018  Latin America and Caribbean        22
2015  Western Europe                     21
2016  Western Europe                     21
2017  Western Europe                     21
2019  Latin America and Caribbean        21
2015  Middle East and Northern Africa    20
2018  Western Europe                     20
      Middle East and Northern Africa    20
2019  Western Europe                     20
      Middle East and Northern Africa    20
2016  Middle East and Northern Africa    19
2017  Middle East and Northern Africa    19
2015  Southeastern Asia                   9
2016  Southeastern Asia                   9
2018  Southeastern Asia                   9
2019  Southeastern Asia                   9
2017  Southeastern Asia                   8
2015  Southern Asia                       7
2016  Southern Asia                       7
2017  Southern Asia                       7
2018  Southern Asia                       7
2019  Southern Asia                       7
2015  Eastern Asia                        6
2016  Eastern Asia                        6
2017  Eastern Asia                        6
2018  Eastern Asia                        6
2019  Eastern Asia                        6
2015  North America                       2
      Australia and New Zealand           2
2016  North America                       2
      Australia and New Zealand           2
2017  North America                       2
      Australia and New Zealand           2
2018  North America                       2
      Australia and New Zealand           2
2019  Australia and New Zealand           2
      North America                       2
Name: count, dtype: int64

In [171]:
display(hapy_country_df.gdp_percapita.duplicated().sum())

np.int64(40)

In [27]:

# 2. Crear columna region para años 2018 y 2019 X
# 3. Decidir que columnas nos quedamos:X
# - country
# - happiness score
# - hapines rank
# - gdp
# - life_expectancy
# - corruption
# - generosity
# - social support==family
# - freedom
# 4. Ver null values en las filas -> quitar, rellenar o sustituir por 0 X
# 5. Ver duplicados por datasets por años -> quitar duplicados x
# 6. Unir todos los datasets en un y crear columna año
year_15.happiness_score.min()

np.float64(2.839)

In [38]:
year_15.select_dtypes(include="number").agg(["min", "max"])

,happiness_rank,happiness_score,standard_error,gdp_percapita,family,life_expectancy,freedom,government_corruption,generosity,dystopia_residual
min,1,2.839,0.01848,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.32858
max,158,7.587,0.13693,1.69042,1.40223,1.02525,0.66973,0.55191,0.79588,3.60214

In [39]:
year_16.select_dtypes(include="number").agg(["min", "max"])

,happiness_rank,happiness_score,lower_confidence_interval,upper_confidence_interval,gdp_percapita,family,life_expectancy,freedom,government_corruption,generosity,dystopia_residual
min,1,2.905,2.732,3.078,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.81789
max,157,7.526,7.460,7.669,1.82427,1.18326,0.95277,0.60848,0.50521,0.81971,3.83772

In [40]:
year_17.select_dtypes(include="number").agg(["min", "max"])

,happiness_rank,happiness_score,whisker_high,whisker_low,gdp_percapita,family,life_expectancy,freedom,generosity,government_corruption,dystopia_residual
min,1,2.693,2.864884,2.521116,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377914
max,155,7.537,7.622030,7.479556,1.870766,1.610574,0.949492,0.658249,0.838075,0.464308,3.117485

In [30]:
!pip3 install pycountry

Requirement already satisfied: pycountry in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (26.2.16)

In [ ]:
Hipotesis_1: 
Hipotesis_2:

In [ ]:
GDP:
educacion:
desempleo:

In [ ]:
HEALTH
nivel privatizacion

In [ ]:
COUNTRY:
population
age of population