In [72]:
import pandas as pd

total_pop = pd.read_csv("total_pop.csv")

In [73]:
total_pop.head()

,IndicatorId,IndicatorName,IndicatorShortName,Source,SourceYear,Author,LocationId,Location,Iso2,Iso3,...,AgeStart,AgeEnd,Age,CategoryId,Category,EstimateTypeId,EstimateType,EstimateMethodId,EstimateMethod,Value
0,49,Total population by sex,Total population by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,3,Projection,33831763.5
1,49,Total population by sex,Total population by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,3,Projection,34700612.0
2,49,Total population by sex,Total population by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,3,Projection,35688934.5
3,49,Total population by sex,Total population by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,3,Projection,36743039.0
4,49,Total population by sex,Total population by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,3,Projection,37856121.0

In [74]:
columns_to_keep = ["Location", "Time", "Value"]
total_pop = total_pop[columns_to_keep]
total_pop.columns

Index(['Location', 'Time', 'Value'], dtype='str')

In [75]:
total_pop = total_pop.rename(columns={"Location": "country","Time": "year","Value": "total_pop"})
total_pop.columns

Index(['country', 'year', 'total_pop'], dtype='str')

In [76]:
pop_density = pd.read_csv("pop_density.csv")
pop_density.head()

,IndicatorId,IndicatorName,IndicatorShortName,Source,SourceYear,Author,LocationId,Location,Iso2,Iso3,...,AgeStart,AgeEnd,Age,CategoryId,Category,EstimateTypeId,EstimateType,EstimateMethodId,EstimateMethod,Value
0,54,Population density,Population density (persons per square km),World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,52.105301
1,54,Population density,Population density (persons per square km),World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,53.443440
2,54,Population density,Population density (persons per square km),World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,54.965585
3,54,Population density,Population density (persons per square km),World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,56.589043
4,54,Population density,Population density (persons per square km),World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,58.303333

In [77]:
columns_to_keep = ["Location", "Time", "Value"]

pop_density = pop_density[columns_to_keep]
pop_density.columns

Index(['Location', 'Time', 'Value'], dtype='str')

In [78]:
pop_density = pop_density.rename(columns={"Location": "country","Time": "year","Value": "pop_density"})

In [79]:
pop_density.head()

       country  year  pop_density
0  Afghanistan  2015    52.105301
1  Afghanistan  2016    53.443440
2  Afghanistan  2017    54.965585
3  Afghanistan  2018    56.589043
4  Afghanistan  2019    58.303333

In [80]:
pop_density.isnull().sum()

country        0
year           0
pop_density    0
dtype: int64

In [81]:
pop_density.duplicated().sum()

np.int64(0)

In [82]:
age_pop= pd.read_csv("age_pop.csv")
display(age_pop.head())

columns_to_keep = ["Location", "Time", "Value"]
age_pop = age_pop[columns_to_keep]
age_pop.columns

,IndicatorId,IndicatorName,IndicatorShortName,Source,SourceYear,Author,LocationId,Location,Iso2,Iso3,...,AgeStart,AgeEnd,Age,CategoryId,Category,EstimateTypeId,EstimateType,EstimateMethodId,EstimateMethod,Value
0,67,Median age of population,Median age of the total population,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,15.489743
1,67,Median age of population,Median age of the total population,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,15.680543
2,67,Median age of population,Median age of the total population,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,15.868287
3,67,Median age of population,Median age of the total population,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,16.050842
4,67,Median age of population,Median age of the total population,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,...,0,-1,Total,0,Not applicable,1,Model-based Estimates,2,Interpolation,16.234260

Index(['Location', 'Time', 'Value'], dtype='str')

In [83]:
age_pop = age_pop.rename(columns={"Location": "country","Time": "year","Value": "age_pop"})
age_pop.columns

Index(['country', 'year', 'age_pop'], dtype='str')

In [84]:
display(age_pop.head())

       country  year    age_pop
0  Afghanistan  2015  15.489743
1  Afghanistan  2016  15.680543
2  Afghanistan  2017  15.868287
3  Afghanistan  2018  16.050842
4  Afghanistan  2019  16.234260

In [85]:
age_pop.isnull().sum()

country    0
year       0
age_pop    0
dtype: int64

In [86]:
display(total_pop.shape)
display(pop_density.shape)
display(age_pop.shape)

(1180, 3)

(1180, 3)

(1180, 3)

In [87]:
population_df = total_pop.merge(pop_density,on=["country", "year"],how="inner").merge(age_pop,on=["country", "year"],how="inner")

In [88]:
display(population_df.head())
display(population_df.shape)
population_df.dtypes

       country  year   total_pop  pop_density    age_pop
0  Afghanistan  2015  33831763.5    52.105301  15.489743
1  Afghanistan  2016  34700612.0    53.443440  15.680543
2  Afghanistan  2017  35688934.5    54.965585  15.868287
3  Afghanistan  2018  36743039.0    56.589043  16.050842
4  Afghanistan  2019  37856121.0    58.303333  16.234260

(1180, 5)

country            str
year             int64
total_pop      float64
pop_density    float64
age_pop        float64
dtype: object

In [89]:
import pycountry
from difflib import get_close_matches

def clean_country_name(country):
    country = country.strip()

    try:
        return pycountry.countries.lookup(country).name
    except LookupError:
        all_country_names = [c.name for c in pycountry.countries]
        match = get_close_matches(country, all_country_names, n=1, cutoff=0.75)

        if match:
            return match[0]
        else:
            return country

population_df["country_clean"] = population_df["country"].apply(clean_country_name)

In [90]:
(population_df["country"] != population_df["country_clean"]).sum()

np.int64(60)

In [91]:
population_df.loc[
    population_df["country"] != population_df["country_clean"],
    ["country", "country_clean"]
].drop_duplicates()

,country,country_clean
95,Bolivia (Plurinational State of),"Bolivia, Plurinational State of"
125,British Virgin Islands,"Virgin Islands, British"
205,"China, Taiwan Province of China","Taiwan, Province of China"
230,Democratic Republic of the Congo,"Congo, The Democratic Republic of the"
470,Iran (Islamic Republic of),"Iran, Islamic Republic of"
660,Republic of Moldova,"Moldova, Republic of"
775,Micronesia (Fed. States of),"Micronesia, Federated States of"
1125,United Republic of Tanzania,"Tanzania, United Republic of"
1130,United States of America,United States
1135,United States Virgin Islands,United States Minor Outlying Islands
1155,Venezuela (Bolivarian Republic of),"Venezuela, Bolivarian Republic of"
1160,Wallis and Futuna Islands,Wallis and Futuna

In [92]:
population_df.country_clean.isna().sum()

np.int64(0)

In [93]:
#Checkcing the countries that didn't find a match using the pycountry library:

bad_countries = []

for country in population_df["country_clean"].unique():
    try:
        pycountry.countries.lookup(country)
    except:
        bad_countries.append(country)

bad_countries

['State of Palestine',
 'China, Hong Kong SAR',
 "Dem. People's Rep. of Korea",
 'Republic of Korea',
 'Kosovo (under UNSC res. 1244)',
 'China, Macao SAR',
 'Saint Helena']

In [95]:
population_country_fixes = {
    "Republic of Korea": "Korea, Republic of",
    "Russian Federation": "Russia",
    "Cyprus": "North Cyprus",
    "Kosovo (under UNSC res. 1244)": "Kosovo",
    "China, Hong Kong SAR": "Hong Kong",
    "Türkiye": "Turkey",
    "North Macedonia": "Macedonia",
    "Eswatini": "Swaziland",
    "State of Palestine": "Palestinian Territories",
    "Democratic Republic of the Congo": "Congo (Kinshasa)",
    "Congo": "Congo (Brazzaville)",
    "Côte d'Ivoire": "Ivory Coast"
}

In [96]:
def fix_population_country(country):
    if country in population_country_fixes:
        return population_country_fixes[country]
    else:
        return country

population_df["country_clean"] = population_df["country_clean"].apply(fix_population_country)

In [97]:
population_df[population_df["country_clean"].isin(population_country_fixes.values())]["country_clean"].unique()

<StringArray>
[    'Congo (Brazzaville)',            'North Cyprus',
 'Palestinian Territories',               'Hong Kong',
             'Ivory Coast',      'Korea, Republic of',
                  'Kosovo',                  'Russia',
               'Swaziland',                  'Turkey',
               'Macedonia']
Length: 11, dtype: str

In [102]:
population_country_fixes = {
    "North Cyprus": "Cyprus",
    "Somalia": "Somaliland region",
    "Congo, The Democratic Republic of the": "Congo (Kinshasa)",
    "Macedonia": "North Macedonia"}
population_df["country_clean"] = population_df["country_clean"].replace(population_country_fixes)

In [103]:
population_df[
    population_df["country_clean"].str.contains(
        "Cyprus|Somali|Congo|Macedonia",
        case=False,
        na=False
    )
]["country_clean"].unique()

<StringArray>
['Congo (Brazzaville)',    'Congo (Kinshasa)',              'Cyprus',
   'Somaliland region',     'North Macedonia']
Length: 5, dtype: str

In [104]:
population_df.to_csv("population_df.csv", index=False)

In [105]:
population_df[
    population_df["country_clean"].isin([
        "North Cyprus",
        "Macedonia",
        "Somalia",
        "Somaliland Region"
    ])
]["country_clean"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [106]:
population_df[
    population_df["country"].isin([
        "North Cyprus",
        "Macedonia",
        "Somalia",
        "Somaliland Region"
    ])
]["country"].unique()

<StringArray>
['Somalia']
Length: 1, dtype: str